import { createSlice } from "@reduxjs/toolkit"

const initialState = {
  permaJewels: {
    white: 0,
    blue: 0,
    green: 0,
    red: 0,
    black: 0,
    pearl: 0,
  },
  jewels: {
    white: 0,
    blue: 0,
    green: 0,
    red: 0,
    black: 0,
    pearl: 0,
    gold: 0,
  },
  points: { white: 0, blue: 0, green: 0, red: 0, black: 0, pearl: 0, gold: 0 },
  crowns: 0,
  scrolls: 1,
  reservedCards: [],
}

export const playerTwoSlice = createSlice({
  name: "playerTwo",
  initialState,
  reducers: {
    getJewel2: (state, x) => {
      console.log("playerTwoSlice")

      for (let i = 0; i < x.payload.length; i++) {
        let myColor = x.payload[i]
        state.jewels[myColor] += 1
      }
    },
    addCard2: (state, x) => {
      console.log("playerTwoSlice")

      if (x.payload.color === "colorless") {
        console.log("colorless thing")
      } else {
        let myColor = x.payload.color
        state.permaJewels[myColor] += x.payload.quantity
        state.points[x.payload.color] += x.payload.points
        state.crowns += x.payload.crowns
      }
    },
    payJewels2: (state, x) => {
      console.log("playerTwoSlice")

      for (let i = 0; i < x.payload.length; i++) {
        state.jewels[x.payload[i]] -= 1
      }
    },
    takeScroll2: (state) => {
      state.scrolls -= 1
    },
    checkWin: (state) => {
      if (state.currPlayer === 2) {
        //end p1 turn

        //check win conditions
        let colorPoints = Object.entries(state.points)
        let maxP = 0
        for (let i = 0; i < colorPoints.length; i++) {
          if (colorPoints[i][1] > maxP) {
            maxP = colorPoints[i][1]
          }
        }
        let pointsTotal = Object.values(state.points).reduce((a, b) => a + b, 0)
        if (state.crowns >= 10 || pointsTotal > 20 || maxP >= 10) {
          state.status = "win"
        }
        //check num jewels
        if (Object.values(state.jewels).reduce((a, b) => a + b, 0) > 10) {
          state.status = "reduce"
        }
        state.currPlayer = 2
      }
    },
    clearStatus2: (state) => {
      state.status = ""
    },
    reserveCards2: (state, x) => {
      state.reservedCards.push(x.payload)
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: () => {},
})

export const {
  addCard2,
  getJewel2,
  payJewels2,
  takeScroll2,
  checkWin,
  clearStatus2,
  reserveCards2,
} = playerTwoSlice.actions

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const showBoard = (state) => state.playerTwo.jewels
// export const getP1Points = (state) => state.playerTwo.points
// export const getP1Crowns = (state) => state.playerTwo.crowns

export default playerTwoSlice.reducer
